// coldframe sound helpers for Remotion. Generated by scripts/build_sfx.py; the files live in public/sfx/.
// Usage:
//   <MusicBed src="music/bed.mp3" duckAt={[240]} />
//   <Sfx role="click-firm" at={96} />            // on the frame the button visibly presses
//   <Sfx role="whoosh" at={150} />               // `at` = the fastest frame of the move; the peak lands there
//   {typingCues(40, 70, cmd.length).map((f, i) => <Sfx key={i} role="key" at={f} />)}
import React from "react";
import { interpolate, Sequence, staticFile, useVideoConfig } from "remotion";
import { Audio } from "@remotion/media";

const LIB = {
  "click-soft": { files: ["click-soft-1.wav", "click-soft-2.wav", "click-soft-3.wav"], peakMs: [19, 8, 8] },
  "click-firm": { files: ["click-firm-1.wav", "click-firm-2.wav", "click-firm-3.wav"], peakMs: [0, 0, 1] },
  "tick": { files: ["tick-1.wav", "tick-2.wav"], peakMs: [1, 1] },
  "key": { files: ["key-1.wav", "key-2.wav", "key-3.wav", "key-4.wav"], peakMs: [5, 7, 26, 17] },
  "key-enter": { files: ["key-enter-1.wav", "key-enter-2.wav"], peakMs: [74, 94] },
  "toggle-on": { files: ["toggle-on.wav"], peakMs: [0] },
  "toggle-off": { files: ["toggle-off.wav"], peakMs: [7] },
  "select": { files: ["select-1.wav", "select-2.wav"], peakMs: [2, 2] },
  "drop": { files: ["drop-1.wav", "drop-2.wav", "drop-3.wav"], peakMs: [0, 0, 1] },
  "pop": { files: ["pop-1.wav", "pop-2.wav"], peakMs: [0, 0] },
  "confirm": { files: ["confirm-1.wav", "confirm-2.wav"], peakMs: [1, 0] },
  "error": { files: ["error.wav"], peakMs: [15] },
  "open": { files: ["open-1.wav", "open-2.wav"], peakMs: [240, 154] },
  "close": { files: ["close-1.wav", "close-2.wav"], peakMs: [1, 55] },
  "whoosh": { files: ["whoosh-1.wav", "whoosh-2.wav"], peakMs: [49, 25] },
  "impact-soft": { files: ["impact-soft-1.wav", "impact-soft-2.wav"], peakMs: [5, 5] },
  "impact": { files: ["impact-1.wav", "impact-2.wav", "impact-3.wav"], peakMs: [6, 7, 16] },
} as const;

export type SfxRole = keyof typeof LIB;

// Sounds that swell into their peak are aligned so the peak (not the start) lands on `at`.
const ALIGN_PEAK: SfxRole[] = ["whoosh", "open", "close"];

/** One sound effect. Variants rotate and pitch varies slightly, so repeats never sound identical. */
export const Sfx: React.FC<{ role: SfxRole; at: number; variant?: number; volume?: number; rate?: number; alignPeak?: boolean }> = ({
  role,
  at,
  variant,
  volume = 1,
  rate,
  alignPeak,
}) => {
  const { fps } = useVideoConfig();
  const lib = LIB[role];
  const i = (variant ?? at) % lib.files.length;
  const r = rate ?? 1 + (((at * 7919) % 9) - 4) * 0.008; // 0.968 - 1.032
  const shift = (alignPeak ?? ALIGN_PEAK.includes(role)) ? Math.round((lib.peakMs[i] / 1000) * fps / r) : 0;
  return (
    <Sequence from={Math.max(0, at - shift)} layout="none" name={`sfx ${role}`}>
      <Audio src={staticFile(`sfx/${lib.files[i]}`)} volume={volume} playbackRate={r} />
    </Sequence>
  );
};

/** Frames for keystroke sounds while `chars` characters are typed between two frames (one tap per ~2 characters). */
export const typingCues = (from: number, to: number, chars: number, charsPerTap = 2): number[] => {
  const taps = Math.max(1, Math.round(chars / charsPerTap));
  return Array.from({ length: taps }, (_, k) => Math.round(from + ((to - from) * k) / taps));
};

/** Soft music bed: fades in and out, ducks around the frames in `duckAt` (big reveals, voiceover lines). */
export const MusicBed: React.FC<{ src: string; volume?: number; duckAt?: number[]; duckTo?: number; fadeIn?: number; fadeOut?: number }> = ({
  src,
  volume = 0.35,
  duckAt = [],
  duckTo = 0.35,
  fadeIn = 1,
  fadeOut = 2,
}) => {
  const { durationInFrames, fps } = useVideoConfig();
  const c = { extrapolateLeft: "clamp", extrapolateRight: "clamp" } as const;
  return (
    <Audio
      src={staticFile(src)}
      volume={(f) => {
        const fade = Math.min(interpolate(f, [0, fadeIn * fps], [0, 1], c), interpolate(f, [durationInFrames - fadeOut * fps, durationInFrames], [1, 0], c));
        const duck = duckAt.reduce((v, at) => v * interpolate(f, [at - 8, at - 2, at + 10, at + 30], [1, duckTo, duckTo, 1], c), 1);
        return volume * fade * duck;
      }}
    />
  );
};
